version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NEXTAUTH_URL=http://localhost:8080
      - NEXTAUTH_URL_INTERNAL=http://host.docker.internal:8080/api/login
      - NEXTAUTH_SECRET=42U94eSbwmDgnwV8egbGUf4iiH0dy1f4s2mHKEP53iw=
      - THINGSBOARD_URL=https://webapp02.heatmanager.cloud
      - MSSQL_USER=hmroot
      - MSSQL_PASSWORD=9YJLpf6CfyteKzoN
      - MSSQL_DATABASE=hmcdev
      - MSSQL_SERVER=hmcdev01.database.windows.net
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway" 